[workspace]
authors = ["Nickolas K Freeman <nick.freeman524@gmail.com>"]
channels = ["conda-forge"]
name = "BAN-501-Spring-2026-ICWIP"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
pyarrow = ">=22.0.0,<23"
polars = ">=1.37.1,<2"
statsmodels = ">=0.14.6,<0.15"
scikit-learn = ">=1.8.0,<2"
pacmap = ">=0.8.0,<0.9"
matplotlib = ">=3.10.8,<4"
seaborn = ">=0.13.2,<0.14"
tqdm = ">=4.67.1,<5"
ipywidgets = ">=8.1.8,<9"
ipython = ">=9.9.0,<10"
marimo = ">=0.19.2,<0.20"
